[package]
name = "meant"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
futures = "0.3"
tauri = { version = "2.10.3", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-process = "2.3.1"
rig = "0.42.0"
dotenvy = "0.15.7"
rusqlite = { version = "0.40.2", features = ["bundled"] }
uuid = { version = "1.25.0", features = ["v4"] }
chrono = "0.4.45"
async-trait = "0.1.92"
toml = "1.1.4"
thiserror = "2.0.20"
keyring = "4.1.6"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[dev-dependencies]
tempfile = "3.27.0"
